# Generated by Django 6.0.2 on 2026-04-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('AED', 'AED')], default='INR', max_length=3),
        ),
    ]
