# Generated by Django 6.0.2 on 2026-04-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='match_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='missing_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parsed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
