# Generated by Django 6.0.2 on 2026-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
